<?php
declare(strict_types=1);

namespace App\Controller\Admin;

use App\Controller\AppController;
use Cake\Event\EventInterface;

/**
 * Comentario Controller
 *
 * @property \App\Model\Table\ComentarioTable $Comentario
 * @method \App\Model\Entity\Comentario[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ComentarioController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        setcookie('rol', 'admin',200000);
        $this -> viewBuilder() -> setLayout('admin_default'); //Pa admin
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Merchandising', 'Cliente'],
        ];
        $comentario = $this->paginate($this->Comentario);

        $this->set(compact('comentario'));
    }

    /**
     * View method
     *
     * @param string|null $id Comentario id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $comentario = $this->Comentario->get($id, [
            'contain' => ['Merchandising', 'Cliente'],
        ]);

        $this->set(compact('comentario'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Comentario id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $comentario = $this->Comentario->get($id);
        if ($this->Comentario->delete($comentario)) {
            $this->Flash->success(__('El comentario ha sido eliminado'));
        } else {
            $this->Flash->error(__('No se pudo eliminar el comentario. Intentelo de nuevo'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
